/*--==========================================
--PROJECT: Sales Performance Analysis
--DATABASE: classicModels
--AUTHOR: Zohra Sayyed 
--DESCRIPTION: 
--This project analyzes sales, customers,
--payments, and product performance using SQL.
--=============================================*/

USE classicmodels;


/*--================================================*/
#--SECTION 1: Customer Payment Analysis
/*--================================================*/
#--Q1:Total payment made by each customer
SELECT customerNumber, SUM(amount) AS total_payment
FROM payments
GROUP BY customerNumber;

#--Q2 Top 5 customer by total payment
SELECT customerNumber,
       SUM(amount) AS total_payment,
	   COUNT(*) AS number_of_payments
FROM payments
GROUP BY customerNumber 
ORDER BY total_payment DESC 
LIMIT 5;        

/*--================================================*/
#--SECTION 2: Customer Details with Payments
/*--================================================*/

#--Q3: Show top 5 customers by total payments along with customer name 
SELECT p.customerNumber,
       c.customerName,
       SUM(amount) total_payment
FROM payments p
JOIN customers c
ON p.customerNumber = c.customerNumber
GROUP BY p.customerNumber,c.customerName
ORDER BY total_payment DESC
LIMIT 5;

/*--================================================*/
#--SECTION 3: Product Sales Performance
/*--================================================*/      

-- #Q4: Which productLine generates the highest total sales
SELECT pr.productLine,
	   SUM(od.priceEach * od.quantityOrdered) AS total_sales
FROM orderDetails od
JOIN products pr
ON od.productCode = pr.productCode
GROUP BY pr.productLine
ORDER BY total_sales DESC;

/*=========================================*/
-- SECTION 4: Order Analysis
/*=========================================*/

#-- Q5: Total number of orders placed by each customer
SELECT customerNumber,
       COUNT(orderNumber) AS total_orders
FROM orders
GROUP BY customerNumber;


/*=========================================
-- SECTION 5: Orders vs Payments Analysis
=========================================*/

#-- Q6: Customers who have placed orders but not made any payments
SELECT o.customerNumber
FROM orders o
LEFT JOIN payments p
  ON o.customerNumber = p.customerNumber
WHERE p.customerNumber IS NULL;


/*=========================================*/
-- SECTION 6: Orders & Revenue Analysis
/*=========================================*/

#-- Q7: Total revenue generated by each order
SELECT od.orderNumber,
       SUM(od.quantityOrdered * od.priceEach) AS order_revenue
FROM orderDetails od
GROUP BY od.orderNumber
ORDER BY order_revenue DESC;
#-- NOTE: orderDetails table already contains quantity and price, so no join is needed here


/*=========================================*/
-- SECTION 7: Time-Based Sales Analysis
/*=========================================*/

#--Q8: Total revenue generated per year 

SELECT 
      YEAR(o.orderDate) AS order_year,
       SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM orders o
JOIN orderDetails od
ON o.orderNumber = od.orderNumber
GROUP BY order_year
ORDER BY total_revenue DESC;

#--Q9: Total revenue by Month 
SELECT
      
      MONTH(o.orderDate) AS order_month,
      SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM orders o
JOIN orderDetails od
ON o.orderNumber = od.orderNumber
GROUP BY order_month
ORDER BY total_revenue DESC;


/*=========================================*/
#--SECTION 8: Business Insights Analysis
/*=========================================*/

#--Q10: Customers who placed orders but never made any payments
#Business meaning:
#“Which customers ordered products but haven’t paid yet?”
SELECT DISTINCT
    o.customerNumber
FROM orders o
LEFT JOIN payments p
    ON o.customerNumber = p.customerNumber
WHERE p.customerNumber IS NULL;

#--Q11: Top 5 highest revenue orders
#Business meaning:
#“Which individual orders earned the most money?”
SELECT
    od.orderNumber,
    SUM(od.quantityOrdered * od.priceEach) AS order_revenue
FROM orderDetails od
GROUP BY od.orderNumber
ORDER BY order_revenue DESC
LIMIT 5;

#--Q12: Average order value (AOV)
#Business meaning:
#"On average, how much money does one order generate?”
SELECT
    AVG(order_total) AS avg_order_value
FROM (
    SELECT
        od.orderNumber,
        SUM(od.quantityOrdered * od.priceEach) AS order_total
    FROM orderDetails od
    GROUP BY od.orderNumber
) t;
